"""initial schema: jobs, tasks, raw_records, pain_signals

Revision ID: eade55a73c8f
Revises: 
Create Date: 2026-05-14 15:21:47.707196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eade55a73c8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_hash', sa.String(length=64), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('job_plan', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_spec_hash'), ['spec_hash'], unique=True)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('wave', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='taskstatus', native_enum=False, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_claim', ['status', 'wave', 'claimed_at'], unique=False)
        batch_op.create_index('ix_tasks_idem', ['job_id', 'content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_tasks_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_tasks_stuck', ['status', 'claimed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_wave'), ['wave'], unique=False)

    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.create_index('ix_raw_job_source', ['job_id', 'source'], unique=False)
        batch_op.create_index('ix_raw_natural', ['source', 'external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_raw_records_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_task_id'), ['task_id'], unique=False)

    op.create_table('pain_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('raw_record_id', sa.Integer(), nullable=False),
    sa.Column('pain_topic', sa.Enum('scheduling', 'billing', 'follow_up', 'lead_response', 'staffing', 'tools', 'other', name='paintopic', native_enum=False, length=32), nullable=False),
    sa.Column('sentiment', sa.Enum('negative', 'neutral', 'positive', name='sentiment', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('industry_signal_strength', sa.Float(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('tools_mentioned', sa.JSON(), nullable=False),
    sa.Column('company_mentions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pain_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pain_signals_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pain_signals_raw_record_id'), ['raw_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pain_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pain_signals_raw_record_id'))
        batch_op.drop_index(batch_op.f('ix_pain_signals_job_id'))

    op.drop_table('pain_signals')
    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_records_task_id'))
        batch_op.drop_index(batch_op.f('ix_raw_records_job_id'))
        batch_op.drop_index('ix_raw_natural')
        batch_op.drop_index('ix_raw_job_source')

    op.drop_table('raw_records')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_wave'))
        batch_op.drop_index('ix_tasks_stuck')
        batch_op.drop_index(batch_op.f('ix_tasks_job_id'))
        batch_op.drop_index('ix_tasks_idem')
        batch_op.drop_index('ix_tasks_claim')

    op.drop_table('tasks')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_spec_hash'))

    op.drop_table('jobs')
    # ### end Alembic commands ###
